tasks:
  - before: pip3 install torch
  - init: pip3 install "modelscope==1.4.2" "open_clip_torch" "pytorch-lightning" "opencv-python"
  - command: python3 main.py --debug "A kitten chasing a butterfly"
